# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import pyo3_quant

__all__ = [
    "run_sensitivity_test",
]

def run_sensitivity_test(
    data_dict: pyo3_quant.DataContainer,
    param: pyo3_quant.SingleParamSet,
    template: pyo3_quant.TemplateContainer,
    engine_settings: pyo3_quant.SettingContainer,
    config: pyo3_quant.SensitivityConfig,
) -> pyo3_quant.SensitivityResult:
    r"""
    运行敏感性测试
    """
