# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from pyo3_quant import _pyo3_quant
import typing

__all__ = [
    "generate_signals",
]

def generate_signals(
    processed_data: _pyo3_quant.DataContainer,
    indicator_dfs_py: typing.Mapping[builtins.str, typing.Any],
    signal_params: typing.Mapping[builtins.str, _pyo3_quant.Param],
    signal_template: _pyo3_quant.SignalTemplate,
) -> typing.Any: ...
