# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import pyo3_quant

__all__ = [
    "run_walk_forward",
]

def run_walk_forward(
    data_dict: pyo3_quant.DataContainer,
    param: pyo3_quant.SingleParamSet,
    template: pyo3_quant.TemplateContainer,
    engine_settings: pyo3_quant.SettingContainer,
    walk_forward_config: pyo3_quant.WalkForwardConfig,
) -> pyo3_quant.WalkForwardResult:
    r"""
    运行滚动前推测试
    """
