# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from pyo3_quant import _pyo3_quant
import typing

__all__ = [
    "analyze_performance",
]

def analyze_performance(
    data_dict: _pyo3_quant.DataContainer,
    backtest_df_py: typing.Any,
    performance_params: _pyo3_quant.PerformanceParams,
) -> builtins.dict[builtins.str, builtins.float]: ...
