# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from pyo3_quant import _pyo3_quant
import typing

__all__ = [
    "py_run_optimizer",
    "py_run_optimizer_benchmark",
]

def py_run_optimizer(
    data_dict: _pyo3_quant.DataContainer,
    param: _pyo3_quant.SingleParamSet,
    template: _pyo3_quant.TemplateContainer,
    engine_settings: _pyo3_quant.SettingContainer,
    optimizer_config: _pyo3_quant.OptimizerConfig,
) -> _pyo3_quant.OptimizationResult:
    r"""
    运行优化器
    """

def py_run_optimizer_benchmark(
    config: _pyo3_quant.OptimizerConfig,
    function: _pyo3_quant.BenchmarkFunction,
    bounds: typing.Sequence[tuple[builtins.float, builtins.float]],
    seed: typing.Optional[builtins.int] = None,
) -> tuple[builtins.list[builtins.float], builtins.float]:
    r"""
    Python 接口：运行基准函数优化
    """
