# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from pyo3_quant import _pyo3_quant
import typing

__all__ = [
    "calculate_indicators",
    "resolve_indicator_contracts",
]

def calculate_indicators(
    processed_data: _pyo3_quant.DataPack,
    indicators_params: typing.Mapping[
        builtins.str,
        typing.Mapping[builtins.str, typing.Mapping[builtins.str, _pyo3_quant.Param]],
    ],
) -> builtins.dict[builtins.str, typing.Any]: ...
def resolve_indicator_contracts(
    indicators_params: typing.Mapping[
        builtins.str,
        typing.Mapping[builtins.str, typing.Mapping[builtins.str, _pyo3_quant.Param]],
    ],
) -> _pyo3_quant.IndicatorContractReport:
    r"""
    计算并返回指标契约聚合结果（供 Python/WF 预检消费）。
    """
