# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from pyo3_quant import _pyo3_quant
import typing

__all__ = [
    "calculate_indicators",
]

def calculate_indicators(
    processed_data: _pyo3_quant.DataContainer,
    indicators_params: typing.Mapping[
        builtins.str,
        typing.Mapping[builtins.str, typing.Mapping[builtins.str, _pyo3_quant.Param]],
    ],
) -> builtins.dict[builtins.str, typing.Any]: ...
