# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import pyo3_quant
from . import action_resolver
from . import backtester
from . import data_ops
from . import indicators
from . import optimizer
from . import performance_analyzer
from . import sensitivity
from . import signal_generator
from . import walk_forward

__all__ = [
    "action_resolver",
    "backtester",
    "data_ops",
    "indicators",
    "optimizer",
    "performance_analyzer",
    "run_batch_backtest",
    "run_single_backtest",
    "sensitivity",
    "signal_generator",
    "walk_forward",
]

def run_batch_backtest(
    data: pyo3_quant.DataPack,
    params: list[pyo3_quant.SingleParamSet],
    template: pyo3_quant.TemplateContainer,
    engine_settings: pyo3_quant.SettingContainer,
) -> list[pyo3_quant.ResultPack]:
    r"""
    运行批量回测
    """

def run_single_backtest(
    data: pyo3_quant.DataPack,
    param: pyo3_quant.SingleParamSet,
    template: pyo3_quant.TemplateContainer,
    engine_settings: pyo3_quant.SettingContainer,
) -> pyo3_quant.ResultPack:
    r"""
    运行单个回测
    """
