# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import pyo3_quant
from . import action_resolver
from . import backtester
from . import indicators
from . import optimizer
from . import performance_analyzer
from . import sensitivity
from . import signal_generator
from . import walk_forward

__all__ = [
    "action_resolver",
    "backtester",
    "indicators",
    "optimizer",
    "performance_analyzer",
    "run_backtest_engine",
    "run_single_backtest",
    "sensitivity",
    "signal_generator",
    "walk_forward",
]

def run_backtest_engine(
    data_dict: pyo3_quant.DataContainer,
    param_set: list[pyo3_quant.SingleParamSet],
    template: pyo3_quant.TemplateContainer,
    engine_settings: pyo3_quant.SettingContainer,
) -> list[pyo3_quant.BacktestSummary]:
    r"""
    运行回测引擎
    """

def run_single_backtest(
    data_dict: pyo3_quant.DataContainer,
    param: pyo3_quant.SingleParamSet,
    template: pyo3_quant.TemplateContainer,
    engine_settings: pyo3_quant.SettingContainer,
) -> pyo3_quant.BacktestSummary:
    r"""
    运行单个回测
    """
