# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from pyo3_quant import _pyo3_quant
import typing

__all__ = [
    "frame_state_name",
    "run_backtest",
]

def frame_state_name(state_id: builtins.int) -> builtins.str:
    r"""
    将状态 ID 转为名称（PyO3 导出，替代 bitmask_to_event_names）
    """

def run_backtest(
    processed_data: _pyo3_quant.DataContainer,
    signals_df_py: typing.Any,
    backtest_params: _pyo3_quant.BacktestParams,
) -> typing.Any:
    r"""
    Python绑定：执行标准回测计算

    对应Rust函数：[`run_backtest`]
    """
