# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import pyo3_quant

__all__ = [
    "build_time_mapping",
    "is_natural_mapping_column",
    "slice_data_container",
]

def build_time_mapping(
    data_dict: pyo3_quant.DataContainer, align_to_base_range: bool = True
) -> pyo3_quant.DataContainer:
    r"""
    在 Rust 端构建 DataContainer.mapping（可选按 base 时间范围对齐）
    """

def is_natural_mapping_column(
    data_dict: pyo3_quant.DataContainer, source_key: str
) -> bool:
    r"""
    判断 mapping[source_key] 是否为 0..n-1 自然序列（fast-path 判定）
    """

def slice_data_container(
    data_dict: pyo3_quant.DataContainer, start: int, length: int
) -> pyo3_quant.DataContainer:
    r"""
    按 base 窗口切 DataContainer，并重基窗口内 mapping
    """
