# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing

__all__ = [
    "BacktestParams",
    "BacktestSummary",
    "BenchmarkFunction",
    "DataContainer",
    "ExecutionStage",
    "LogicOp",
    "OptimizationResult",
    "OptimizeMetric",
    "OptimizerConfig",
    "Param",
    "ParamType",
    "PerformanceMetric",
    "PerformanceParams",
    "RoundSummary",
    "SamplePoint",
    "SensitivityConfig",
    "SensitivityResult",
    "SensitivitySample",
    "SettingContainer",
    "SignalGroup",
    "SignalTemplate",
    "SingleParamSet",
    "TemplateContainer",
    "WalkForwardConfig",
    "WalkForwardResult",
    "WindowResult",
]

@typing.final
class BacktestParams:
    r"""
    回测引擎的参数结构体。
    包含止损止盈、ATR、资金管理、手续费等所有可配置参数。
    参数值为 `Param` 类型，通过 `.value` 访问实际数值。
    """
    @property
    def sl_pct(self) -> typing.Optional[Param]:
        r"""
        百分比止损阈值。当仓位亏损达到此百分比时触发止损。
        如果值 <= 0.0，则不使用百分比止损功能。
        """
    @sl_pct.setter
    def sl_pct(self, value: typing.Optional[Param]) -> None:
        r"""
        百分比止损阈值。当仓位亏损达到此百分比时触发止损。
        如果值 <= 0.0，则不使用百分比止损功能。
        """
    @property
    def tp_pct(self) -> typing.Optional[Param]:
        r"""
        百分比止盈阈值。当仓位盈利达到此百分比时触发止盈。
        如果值 <= 0.0，则不使用百分比止盈功能。
        """
    @tp_pct.setter
    def tp_pct(self, value: typing.Optional[Param]) -> None:
        r"""
        百分比止盈阈值。当仓位盈利达到此百分比时触发止盈。
        如果值 <= 0.0，则不使用百分比止盈功能。
        """
    @property
    def tsl_pct(self) -> typing.Optional[Param]:
        r"""
        百分比跟踪止损阈值。当仓位盈利回撤达到此百分比时触发跟踪止损。
        如果值 <= 0.0，则不使用百分比跟踪止损功能。
        """
    @tsl_pct.setter
    def tsl_pct(self, value: typing.Optional[Param]) -> None:
        r"""
        百分比跟踪止损阈值。当仓位盈利回撤达到此百分比时触发跟踪止损。
        如果值 <= 0.0，则不使用百分比跟踪止损功能。
        """
    @property
    def sl_atr(self) -> typing.Optional[Param]:
        r"""
        ATR止损倍数。止损价格基于入场价格减去ATR值乘以该倍数。
        如果值 <= 0.0，则不使用ATR止损功能。
        依赖 `atr_period`，如果 `atr_period` <= 0.0，即使 `sl_atr` > 0.0 也不会启用。
        """
    @sl_atr.setter
    def sl_atr(self, value: typing.Optional[Param]) -> None:
        r"""
        ATR止损倍数。止损价格基于入场价格减去ATR值乘以该倍数。
        如果值 <= 0.0，则不使用ATR止损功能。
        依赖 `atr_period`，如果 `atr_period` <= 0.0，即使 `sl_atr` > 0.0 也不会启用。
        """
    @property
    def tp_atr(self) -> typing.Optional[Param]:
        r"""
        ATR止盈倍数。止盈价格基于入场价格加上ATR值乘以该倍数。
        如果值 <= 0.0，则不使用ATR止盈功能。
        依赖 `atr_period`，如果 `atr_period` <= 0.0，即使 `tp_atr` > 0.0 也不会启用。
        """
    @tp_atr.setter
    def tp_atr(self, value: typing.Optional[Param]) -> None:
        r"""
        ATR止盈倍数。止盈价格基于入场价格加上ATR值乘以该倍数。
        如果值 <= 0.0，则不使用ATR止盈功能。
        依赖 `atr_period`，如果 `atr_period` <= 0.0，即使 `tp_atr` > 0.0 也不会启用。
        """
    @property
    def tsl_atr(self) -> typing.Optional[Param]:
        r"""
        ATR跟踪止损倍数。跟踪止损价格基于最高价减去ATR值乘以该倍数。
        如果值 <= 0.0，则不使用ATR跟踪止损功能。
        依赖 `atr_period`，如果 `atr_period` <= 0.0，即使 `tsl_atr` > 0.0 也不会启用。
        """
    @tsl_atr.setter
    def tsl_atr(self, value: typing.Optional[Param]) -> None:
        r"""
        ATR跟踪止损倍数。跟踪止损价格基于最高价减去ATR值乘以该倍数。
        如果值 <= 0.0，则不使用ATR跟踪止损功能。
        依赖 `atr_period`，如果 `atr_period` <= 0.0，即使 `tsl_atr` > 0.0 也不会启用。
        """
    @property
    def atr_period(self) -> typing.Optional[Param]:
        r"""
        ATR计算周期。用于计算平均真实范围 (ATR) 的K线周期数。
        如果值 <= 0.0，则所有ATR相关的止损止盈功能都不会启用。
        """
    @atr_period.setter
    def atr_period(self, value: typing.Optional[Param]) -> None:
        r"""
        ATR计算周期。用于计算平均真实范围 (ATR) 的K线周期数。
        如果值 <= 0.0，则所有ATR相关的止损止盈功能都不会启用。
        """
    @property
    def tsl_psar_af0(self) -> typing.Optional[Param]:
        r"""
        PSAR 初始加速因子。
        三个参数必须同时存在或同时不存在，存在时都必须大于0。
        """
    @tsl_psar_af0.setter
    def tsl_psar_af0(self, value: typing.Optional[Param]) -> None:
        r"""
        PSAR 初始加速因子。
        三个参数必须同时存在或同时不存在，存在时都必须大于0。
        """
    @property
    def tsl_psar_af_step(self) -> typing.Optional[Param]:
        r"""
        PSAR 加速因子步进。
        """
    @tsl_psar_af_step.setter
    def tsl_psar_af_step(self, value: typing.Optional[Param]) -> None:
        r"""
        PSAR 加速因子步进。
        """
    @property
    def tsl_psar_max_af(self) -> typing.Optional[Param]:
        r"""
        PSAR 最大加速因子。
        """
    @tsl_psar_max_af.setter
    def tsl_psar_max_af(self, value: typing.Optional[Param]) -> None:
        r"""
        PSAR 最大加速因子。
        """
    @property
    def tsl_atr_tight(self) -> builtins.bool:
        r"""
        ATR跟踪止损更新模式。
        `false` (默认) 表示只有在价格突破新高/低时才更新TSL ATR价格。
        `true` 表示每根K线都会尝试更新TSL ATR价格。
        无论设置如何，多头TSL只能上移，空头TSL只能下移。
        """
    @tsl_atr_tight.setter
    def tsl_atr_tight(self, value: builtins.bool) -> None:
        r"""
        ATR跟踪止损更新模式。
        `false` (默认) 表示只有在价格突破新高/低时才更新TSL ATR价格。
        `true` 表示每根K线都会尝试更新TSL ATR价格。
        无论设置如何，多头TSL只能上移，空头TSL只能下移。
        """
    @property
    def sl_exit_in_bar(self) -> builtins.bool:
        r"""
        sl 离场时机选择。
        `true` 表示在当前K线内部触发条件时立即离场。
        `false` 表示延迟到下一根K线的开盘价离场。
        """
    @sl_exit_in_bar.setter
    def sl_exit_in_bar(self, value: builtins.bool) -> None:
        r"""
        sl 离场时机选择。
        `true` 表示在当前K线内部触发条件时立即离场。
        `false` 表示延迟到下一根K线的开盘价离场。
        """
    @property
    def tp_exit_in_bar(self) -> builtins.bool:
        r"""
        tp 离场时机选择。
        `true` 表示在当前K线内部触发条件时立即离场。
        `false` 表示延迟到下一根K线的开盘价离场。
        """
    @tp_exit_in_bar.setter
    def tp_exit_in_bar(self, value: builtins.bool) -> None:
        r"""
        tp 离场时机选择。
        `true` 表示在当前K线内部触发条件时立即离场。
        `false` 表示延迟到下一根K线的开盘价离场。
        """
    @property
    def sl_trigger_mode(self) -> builtins.bool:
        r"""
        SL 触发模式
        """
    @sl_trigger_mode.setter
    def sl_trigger_mode(self, value: builtins.bool) -> None:
        r"""
        SL 触发模式
        """
    @property
    def tp_trigger_mode(self) -> builtins.bool:
        r"""
        TP 触发模式
        """
    @tp_trigger_mode.setter
    def tp_trigger_mode(self, value: builtins.bool) -> None:
        r"""
        TP 触发模式
        """
    @property
    def tsl_trigger_mode(self) -> builtins.bool:
        r"""
        TSL 触发模式 (含 tsl_atr, tsl_pct, tsl_psar)
        """
    @tsl_trigger_mode.setter
    def tsl_trigger_mode(self, value: builtins.bool) -> None:
        r"""
        TSL 触发模式 (含 tsl_atr, tsl_pct, tsl_psar)
        """
    @property
    def sl_anchor_mode(self) -> builtins.bool:
        r"""
        SL 锚点模式
        """
    @sl_anchor_mode.setter
    def sl_anchor_mode(self, value: builtins.bool) -> None:
        r"""
        SL 锚点模式
        """
    @property
    def tp_anchor_mode(self) -> builtins.bool:
        r"""
        TP 锚点模式
        """
    @tp_anchor_mode.setter
    def tp_anchor_mode(self, value: builtins.bool) -> None:
        r"""
        TP 锚点模式
        """
    @property
    def tsl_anchor_mode(self) -> builtins.bool:
        r"""
        TSL 锚点模式 (仅影响 tsl_atr, tsl_pct，不影响 tsl_psar)
        """
    @tsl_anchor_mode.setter
    def tsl_anchor_mode(self, value: builtins.bool) -> None:
        r"""
        TSL 锚点模式 (仅影响 tsl_atr, tsl_pct，不影响 tsl_psar)
        """
    @property
    def initial_capital(self) -> builtins.float:
        r"""
        初始本金。回测开始时的账户资金量 (USD)。
        必须大于 0.0。
        """
    @initial_capital.setter
    def initial_capital(self, value: builtins.float) -> None:
        r"""
        初始本金。回测开始时的账户资金量 (USD)。
        必须大于 0.0。
        """
    @property
    def fee_fixed(self) -> builtins.float:
        r"""
        固定手续费。每笔交易的固定手续费金额 (USD)。
        必须 >= 0.0。
        """
    @fee_fixed.setter
    def fee_fixed(self, value: builtins.float) -> None:
        r"""
        固定手续费。每笔交易的固定手续费金额 (USD)。
        必须 >= 0.0。
        """
    @property
    def fee_pct(self) -> builtins.float:
        r"""
        百分比手续费。每笔交易金额的百分比手续费。
        必须 >= 0.0。
        """
    @fee_pct.setter
    def fee_pct(self, value: builtins.float) -> None:
        r"""
        百分比手续费。每笔交易金额的百分比手续费。
        必须 >= 0.0。
        """
    def __new__(
        cls,
        *,
        sl_pct: typing.Optional[Param] = None,
        tp_pct: typing.Optional[Param] = None,
        tsl_pct: typing.Optional[Param] = None,
        sl_atr: typing.Optional[Param] = None,
        tp_atr: typing.Optional[Param] = None,
        tsl_atr: typing.Optional[Param] = None,
        atr_period: typing.Optional[Param] = None,
        tsl_psar_af0: typing.Optional[Param] = None,
        tsl_psar_af_step: typing.Optional[Param] = None,
        tsl_psar_max_af: typing.Optional[Param] = None,
        tsl_atr_tight: builtins.bool = False,
        sl_exit_in_bar: builtins.bool = True,
        tp_exit_in_bar: builtins.bool = True,
        sl_trigger_mode: builtins.bool = True,
        tp_trigger_mode: builtins.bool = True,
        tsl_trigger_mode: builtins.bool = True,
        sl_anchor_mode: builtins.bool = False,
        tp_anchor_mode: builtins.bool = False,
        tsl_anchor_mode: builtins.bool = False,
        initial_capital: builtins.float = 10000.0,
        fee_fixed: builtins.float = 0.0,
        fee_pct: builtins.float = 0.0006,
    ) -> BacktestParams: ...
    def set_optimizable_param(
        self, name: builtins.str, value: typing.Optional[Param]
    ) -> None:
        r"""
        业务层设置可优化参数（Option<Param> 字段）。
        使用字段名精确更新，避免在 Python 侧做深层读改写回。
        """
    def set_bool_param(self, name: builtins.str, value: builtins.bool) -> None:
        r"""
        业务层设置布尔参数。
        """
    def set_f64_param(self, name: builtins.str, value: builtins.float) -> None:
        r"""
        业务层设置数值参数。
        """

@typing.final
class BacktestSummary:
    @property
    def indicators(self) -> typing.Optional[dict]: ...
    @indicators.setter
    def indicators(
        self, value: typing.Optional[builtins.dict[builtins.str, typing.Any]]
    ) -> None: ...
    @property
    def signals(self) -> typing.Optional[typing.Any]: ...
    @signals.setter
    def signals(self, value: typing.Optional[typing.Any]) -> None: ...
    @property
    def backtest_result(self) -> typing.Optional[typing.Any]: ...
    @backtest_result.setter
    def backtest_result(self, value: typing.Optional[typing.Any]) -> None: ...
    @property
    def performance(
        self,
    ) -> typing.Optional[builtins.dict[builtins.str, builtins.float]]: ...
    @performance.setter
    def performance(
        self, value: typing.Optional[builtins.dict[builtins.str, builtins.float]]
    ) -> None: ...
    def __new__(
        cls,
        performance: typing.Optional[
            typing.Mapping[builtins.str, builtins.float]
        ] = None,
        indicators: typing.Optional[typing.Mapping[builtins.str, typing.Any]] = None,
        signals: typing.Optional[typing.Any] = None,
        backtest_result: typing.Optional[typing.Any] = None,
    ) -> BacktestSummary: ...

@typing.final
class DataContainer:
    @property
    def mapping(self) -> typing.Any: ...
    @mapping.setter
    def mapping(self, value: typing.Any) -> None: ...
    @property
    def skip_mask(self) -> typing.Optional[typing.Any]: ...
    @skip_mask.setter
    def skip_mask(self, value: typing.Optional[typing.Any]) -> None: ...
    @property
    def source(self) -> builtins.dict[builtins.str, typing.Any]: ...
    @source.setter
    def source(self, value: builtins.dict[builtins.str, typing.Any]) -> None: ...
    @property
    def base_data_key(self) -> builtins.str: ...
    @base_data_key.setter
    def base_data_key(self, value: builtins.str) -> None: ...
    @property
    def skip_mapping(self) -> builtins.dict[builtins.str, builtins.bool]: ...
    @skip_mapping.setter
    def skip_mapping(
        self, value: builtins.dict[builtins.str, builtins.bool]
    ) -> None: ...
    def __new__(
        cls,
        mapping: typing.Any,
        skip_mask: typing.Optional[typing.Any],
        skip_mapping: typing.Mapping[builtins.str, builtins.bool],
        source: typing.Mapping[builtins.str, typing.Any],
        base_data_key: builtins.str,
    ) -> DataContainer: ...

@typing.final
class OptimizationResult:
    @property
    def best_params(self) -> SingleParamSet:
        r"""
        最优参数集 (完整结构，value 已更新)
        """
    @property
    def optimize_metric(self) -> OptimizeMetric:
        r"""
        优化目标
        """
    @property
    def optimize_value(self) -> builtins.float: ...
    @property
    def metrics(self) -> builtins.dict[builtins.str, builtins.float]:
        r"""
        所有计算的性能指标
        """
    @property
    def total_samples(self) -> builtins.int:
        r"""
        统计
        """
    @property
    def rounds(self) -> builtins.int: ...
    @property
    def history(self) -> builtins.list[RoundSummary]: ...
    @property
    def top_k_params(self) -> builtins.list[SingleParamSet]:
        r"""
        Top K 参数集 (用于 WF 热启动)
        """
    @property
    def top_k_samples(self) -> builtins.list[SamplePoint]: ...

@typing.final
class OptimizerConfig:
    @property
    def explore_ratio(self) -> builtins.float: ...
    @explore_ratio.setter
    def explore_ratio(self, value: builtins.float) -> None: ...
    @property
    def sigma_ratio(self) -> builtins.float: ...
    @sigma_ratio.setter
    def sigma_ratio(self, value: builtins.float) -> None: ...
    @property
    def weight_decay(self) -> builtins.float: ...
    @weight_decay.setter
    def weight_decay(self, value: builtins.float) -> None: ...
    @property
    def top_k_ratio(self) -> builtins.float: ...
    @top_k_ratio.setter
    def top_k_ratio(self, value: builtins.float) -> None: ...
    @property
    def samples_per_round(self) -> builtins.int: ...
    @samples_per_round.setter
    def samples_per_round(self, value: builtins.int) -> None: ...
    @property
    def max_samples(self) -> builtins.int:
        r"""
        最大采样数量
        """
    @max_samples.setter
    def max_samples(self, value: builtins.int) -> None:
        r"""
        最大采样数量
        """
    @property
    def min_samples(self) -> builtins.int:
        r"""
        最小采样数量（至少运行这么多次才会检查停止条件）
        """
    @min_samples.setter
    def min_samples(self, value: builtins.int) -> None:
        r"""
        最小采样数量（至少运行这么多次才会检查停止条件）
        """
    @property
    def max_rounds(self) -> builtins.int:
        r"""
        最大迭代轮数
        """
    @max_rounds.setter
    def max_rounds(self, value: builtins.int) -> None:
        r"""
        最大迭代轮数
        """
    @property
    def stop_patience(self) -> builtins.int:
        r"""
        停止条件：连续多少轮没有创新高则停止
        """
    @stop_patience.setter
    def stop_patience(self, value: builtins.int) -> None:
        r"""
        停止条件：连续多少轮没有创新高则停止
        """
    @property
    def optimize_metric(self) -> OptimizeMetric:
        r"""
        优化目标指标
        """
    @optimize_metric.setter
    def optimize_metric(self, value: OptimizeMetric) -> None:
        r"""
        优化目标指标
        """
    @property
    def init_samples(
        self,
    ) -> typing.Optional[builtins.list[builtins.list[builtins.float]]]:
        r"""
        初始采样点（用于热启动）
        """
    @init_samples.setter
    def init_samples(
        self, value: typing.Optional[builtins.list[builtins.list[builtins.float]]]
    ) -> None:
        r"""
        初始采样点（用于热启动）
        """
    @property
    def return_top_k(self) -> builtins.int:
        r"""
        返回 Top K 参数集数量 (0 = 不返回)
        """
    @return_top_k.setter
    def return_top_k(self, value: builtins.int) -> None:
        r"""
        返回 Top K 参数集数量 (0 = 不返回)
        """
    @property
    def seed(self) -> typing.Optional[builtins.int]:
        r"""
        随机种子（None 表示使用系统随机源）
        """
    @seed.setter
    def seed(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        随机种子（None 表示使用系统随机源）
        """
    def __new__(
        cls,
        *,
        explore_ratio: builtins.float = 0.2,
        sigma_ratio: builtins.float = 0.1,
        weight_decay: builtins.float = 0.15,
        top_k_ratio: builtins.float = 0.7,
        samples_per_round: builtins.int = 100,
        max_samples: builtins.int = 10000,
        min_samples: builtins.int = 400,
        max_rounds: builtins.int = 200,
        stop_patience: builtins.int = 10,
        optimize_metric: OptimizeMetric = OptimizeMetric.CalmarRatioRaw,
        init_samples: typing.Optional[
            typing.Sequence[typing.Sequence[builtins.float]]
        ] = None,
        return_top_k: builtins.int = 10,
        seed: typing.Optional[builtins.int] = None,
    ) -> OptimizerConfig: ...

@typing.final
class Param:
    @property
    def value(self) -> builtins.float:
        r"""
        当前参数值
        """
    @value.setter
    def value(self, value: builtins.float) -> None:
        r"""
        当前参数值
        """
    @property
    def min(self) -> builtins.float:
        r"""
        参数最小值限制
        """
    @min.setter
    def min(self, value: builtins.float) -> None:
        r"""
        参数最小值限制
        """
    @property
    def max(self) -> builtins.float:
        r"""
        参数最大值限制
        """
    @max.setter
    def max(self, value: builtins.float) -> None:
        r"""
        参数最大值限制
        """
    @property
    def dtype(self) -> ParamType:
        r"""
        参数类型
        """
    @dtype.setter
    def dtype(self, value: ParamType) -> None:
        r"""
        参数类型
        """
    @property
    def optimize(self) -> builtins.bool:
        r"""
        是否开启参数优化，在参数优化过程中使用
        """
    @optimize.setter
    def optimize(self, value: builtins.bool) -> None:
        r"""
        是否开启参数优化，在参数优化过程中使用
        """
    @property
    def log_scale(self) -> builtins.bool:
        r"""
        是否开启对数分布，用于参数优化时的采样策略
        """
    @log_scale.setter
    def log_scale(self, value: builtins.bool) -> None:
        r"""
        是否开启对数分布，用于参数优化时的采样策略
        """
    @property
    def step(self) -> builtins.float:
        r"""
        最小精度
        """
    @step.setter
    def step(self, value: builtins.float) -> None:
        r"""
        最小精度
        """
    def __new__(
        cls,
        value: builtins.float,
        min: typing.Optional[builtins.float] = None,
        max: typing.Optional[builtins.float] = None,
        dtype: typing.Optional[ParamType] = None,
        optimize: builtins.bool = False,
        log_scale: builtins.bool = False,
        step: builtins.float = 0.01,
    ) -> Param: ...

@typing.final
class PerformanceParams:
    @property
    def metrics(self) -> builtins.list[PerformanceMetric]: ...
    @metrics.setter
    def metrics(self, value: builtins.list[PerformanceMetric]) -> None: ...
    @property
    def risk_free_rate(self) -> builtins.float: ...
    @risk_free_rate.setter
    def risk_free_rate(self, value: builtins.float) -> None: ...
    @property
    def leverage_safety_factor(self) -> typing.Optional[builtins.float]: ...
    @leverage_safety_factor.setter
    def leverage_safety_factor(
        self, value: typing.Optional[builtins.float]
    ) -> None: ...
    def __new__(
        cls,
        *,
        metrics: typing.Optional[typing.Sequence[PerformanceMetric]] = None,
        risk_free_rate: builtins.float = 0.0,
        leverage_safety_factor: typing.Optional[builtins.float] = None,
    ) -> PerformanceParams: ...
    def apply_metrics(self, metrics: typing.Sequence[PerformanceMetric]) -> None:
        r"""
        业务层设置绩效指标列表。
        """
    def apply_risk_free_rate(self, value: builtins.float) -> None:
        r"""
        业务层设置无风险利率。
        """
    def apply_leverage_safety_factor(
        self, value: typing.Optional[builtins.float]
    ) -> None:
        r"""
        业务层设置杠杆安全系数。
        """

@typing.final
class RoundSummary:
    @property
    def round(self) -> builtins.int: ...
    @property
    def best_value(self) -> builtins.float: ...
    @property
    def median_value(self) -> builtins.float: ...
    @property
    def sample_count(self) -> builtins.int: ...

@typing.final
class SamplePoint:
    r"""
    采样点结构
    """
    @property
    def values(self) -> builtins.list[builtins.float]:
        r"""
        各维度的参数值
        """
    @property
    def metric_value(self) -> builtins.float:
        r"""
        该参数组合的目标指标值（由 optimize_metric 指定）
        """
    @property
    def all_metrics(self) -> builtins.dict[builtins.str, builtins.float]:
        r"""
        所有已计算的性能指标
        """

@typing.final
class SensitivityConfig:
    r"""
    敏感性测试配置
    """
    @property
    def jitter_ratio(self) -> builtins.float:
        r"""
        抖动比例 (例如 0.05 代表 +/- 5%)
        """
    @jitter_ratio.setter
    def jitter_ratio(self, value: builtins.float) -> None:
        r"""
        抖动比例 (例如 0.05 代表 +/- 5%)
        """
    @property
    def n_samples(self) -> builtins.int:
        r"""
        采样次数
        """
    @n_samples.setter
    def n_samples(self, value: builtins.int) -> None:
        r"""
        采样次数
        """
    @property
    def distribution(self) -> builtins.str:
        r"""
        分布类型: "uniform" (默认) 或 "normal"
        """
    @distribution.setter
    def distribution(self, value: builtins.str) -> None:
        r"""
        分布类型: "uniform" (默认) 或 "normal"
        """
    @property
    def seed(self) -> typing.Optional[builtins.int]:
        r"""
        随机种子 (保证可复现)
        """
    @seed.setter
    def seed(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        随机种子 (保证可复现)
        """
    @property
    def metric(self) -> OptimizeMetric:
        r"""
        评价指标 (默认 CalmarRatioRaw)
        """
    @metric.setter
    def metric(self, value: OptimizeMetric) -> None:
        r"""
        评价指标 (默认 CalmarRatioRaw)
        """
    def __new__(
        cls,
        *,
        jitter_ratio: builtins.float = 0.05,
        n_samples: builtins.int = 100,
        distribution: builtins.str = "uniform",
        seed: typing.Optional[builtins.int] = None,
        metric: OptimizeMetric = OptimizeMetric.CalmarRatioRaw,
    ) -> SensitivityConfig: ...

@typing.final
class SensitivityResult:
    r"""
    敏感性测试总结果
    """
    @property
    def target_metric(self) -> builtins.str: ...
    @property
    def original_value(self) -> builtins.float: ...
    @property
    def samples(self) -> builtins.list[SensitivitySample]: ...
    @property
    def mean(self) -> builtins.float: ...
    @property
    def std(self) -> builtins.float: ...
    @property
    def min(self) -> builtins.float: ...
    @property
    def max(self) -> builtins.float: ...
    @property
    def median(self) -> builtins.float: ...
    @property
    def cv(self) -> builtins.float: ...
    def report(self) -> builtins.str:
        r"""
        生成敏感性分析报告文本
        """

@typing.final
class SensitivitySample:
    r"""
    单个样本的测试结果
    """
    @property
    def values(self) -> builtins.list[builtins.float]:
        r"""
        采样后的参数值
        """
    @property
    def metric_value(self) -> builtins.float:
        r"""
        目标指标值
        """
    @property
    def all_metrics(self) -> builtins.dict[builtins.str, builtins.float]:
        r"""
        所有性能指标
        """

@typing.final
class SettingContainer:
    @property
    def execution_stage(self) -> ExecutionStage: ...
    @execution_stage.setter
    def execution_stage(self, value: ExecutionStage) -> None: ...
    @property
    def return_only_final(self) -> builtins.bool: ...
    @return_only_final.setter
    def return_only_final(self, value: builtins.bool) -> None: ...
    def __new__(
        cls,
        *,
        execution_stage: ExecutionStage = ExecutionStage.Performance,
        return_only_final: builtins.bool = False,
    ) -> SettingContainer: ...

@typing.final
class SignalGroup:
    @property
    def logic(self) -> LogicOp: ...
    @logic.setter
    def logic(self, value: LogicOp) -> None: ...
    @property
    def comparisons(self) -> builtins.list[builtins.str]:
        r"""
        条件字符串列表，每个字符串会被 nom 解析器转换成 SignalCondition
        语法：`[!] LeftOperand Op RightOperand`
        示例：`"close, ohlcv_15m, 0 > sma_0, ohlcv_15m, 0"` 或 `"rsi_0, ohlcv_1h, 0 < $rsi_lower"`
        """
    @comparisons.setter
    def comparisons(self, value: builtins.list[builtins.str]) -> None:
        r"""
        条件字符串列表，每个字符串会被 nom 解析器转换成 SignalCondition
        语法：`[!] LeftOperand Op RightOperand`
        示例：`"close, ohlcv_15m, 0 > sma_0, ohlcv_15m, 0"` 或 `"rsi_0, ohlcv_1h, 0 < $rsi_lower"`
        """
    @property
    def sub_groups(self) -> builtins.list[SignalGroup]: ...
    @sub_groups.setter
    def sub_groups(self, value: builtins.list[SignalGroup]) -> None: ...
    def __new__(
        cls,
        *,
        logic: LogicOp,
        comparisons: typing.Optional[typing.Sequence[builtins.str]] = None,
        sub_groups: typing.Optional[typing.Sequence[SignalGroup]] = None,
    ) -> SignalGroup: ...

@typing.final
class SignalTemplate:
    @property
    def entry_long(self) -> typing.Optional[SignalGroup]: ...
    @entry_long.setter
    def entry_long(self, value: typing.Optional[SignalGroup]) -> None: ...
    @property
    def exit_long(self) -> typing.Optional[SignalGroup]: ...
    @exit_long.setter
    def exit_long(self, value: typing.Optional[SignalGroup]) -> None: ...
    @property
    def entry_short(self) -> typing.Optional[SignalGroup]: ...
    @entry_short.setter
    def entry_short(self, value: typing.Optional[SignalGroup]) -> None: ...
    @property
    def exit_short(self) -> typing.Optional[SignalGroup]: ...
    @exit_short.setter
    def exit_short(self, value: typing.Optional[SignalGroup]) -> None: ...
    def __new__(
        cls,
        *,
        entry_long: typing.Optional[SignalGroup] = None,
        exit_long: typing.Optional[SignalGroup] = None,
        entry_short: typing.Optional[SignalGroup] = None,
        exit_short: typing.Optional[SignalGroup] = None,
    ) -> SignalTemplate: ...

@typing.final
class SingleParamSet:
    @property
    def indicators(
        self,
    ) -> builtins.dict[
        builtins.str, builtins.dict[builtins.str, builtins.dict[builtins.str, Param]]
    ]: ...
    @indicators.setter
    def indicators(
        self,
        value: builtins.dict[
            builtins.str,
            builtins.dict[builtins.str, builtins.dict[builtins.str, Param]],
        ],
    ) -> None: ...
    @property
    def signal(self) -> builtins.dict[builtins.str, Param]: ...
    @signal.setter
    def signal(self, value: builtins.dict[builtins.str, Param]) -> None: ...
    @property
    def backtest(self) -> BacktestParams: ...
    @backtest.setter
    def backtest(self, value: BacktestParams) -> None: ...
    @property
    def performance(self) -> PerformanceParams: ...
    @performance.setter
    def performance(self, value: PerformanceParams) -> None: ...
    def __new__(
        cls,
        *,
        indicators: typing.Optional[
            typing.Mapping[
                builtins.str,
                typing.Mapping[builtins.str, typing.Mapping[builtins.str, Param]],
            ]
        ] = None,
        signal: typing.Optional[typing.Mapping[builtins.str, Param]] = None,
        backtest: typing.Optional[BacktestParams] = None,
        performance: typing.Optional[PerformanceParams] = None,
    ) -> SingleParamSet: ...
    def set_indicators_params(
        self,
        indicators: typing.Mapping[
            builtins.str,
            typing.Mapping[builtins.str, typing.Mapping[builtins.str, Param]],
        ],
    ) -> None:
        r"""
        业务层一次性替换指标参数容器。
        """
    def set_signal_params(self, signal: typing.Mapping[builtins.str, Param]) -> None:
        r"""
        业务层一次性替换信号参数容器。
        """
    def set_backtest_params(self, backtest: BacktestParams) -> None:
        r"""
        业务层一次性替换回测参数容器。
        """
    def set_performance_params(self, performance: PerformanceParams) -> None:
        r"""
        业务层一次性替换绩效参数容器。
        """
    def set_indicator_param(
        self,
        data_key: builtins.str,
        indicator_name: builtins.str,
        param_name: builtins.str,
        param: Param,
    ) -> None:
        r"""
        业务层设置单个指标参数，按 data_key/indicator/param_name 精确落位。
        """
    def set_signal_param(self, name: builtins.str, param: Param) -> None:
        r"""
        业务层设置单个信号参数。
        """
    def set_backtest_optimizable_param(
        self, name: builtins.str, value: typing.Optional[Param]
    ) -> None:
        r"""
        业务层设置回测可优化参数（Option<Param> 字段）。
        """
    def set_backtest_bool_param(self, name: builtins.str, value: builtins.bool) -> None:
        r"""
        业务层设置回测布尔参数。
        """
    def set_backtest_f64_param(self, name: builtins.str, value: builtins.float) -> None:
        r"""
        业务层设置回测数值参数。
        """
    def set_performance_metrics(
        self, metrics: typing.Sequence[PerformanceMetric]
    ) -> None:
        r"""
        业务层设置绩效指标列表。
        """
    def set_performance_risk_free_rate(self, value: builtins.float) -> None:
        r"""
        业务层设置绩效无风险利率。
        """
    def set_performance_leverage_safety_factor(
        self, value: typing.Optional[builtins.float]
    ) -> None:
        r"""
        业务层设置杠杆安全系数。
        """

@typing.final
class TemplateContainer:
    @property
    def signal(self) -> SignalTemplate: ...
    @signal.setter
    def signal(self, value: SignalTemplate) -> None: ...
    def __new__(cls, signal: SignalTemplate) -> TemplateContainer: ...

@typing.final
class WalkForwardConfig:
    r"""
    向前滚动优化配置
    """
    @property
    def train_ratio(self) -> builtins.float:
        r"""
        训练窗口长度（占总数据的比例），默认 0.60
        """
    @train_ratio.setter
    def train_ratio(self, value: builtins.float) -> None:
        r"""
        训练窗口长度（占总数据的比例），默认 0.60
        """
    @property
    def test_ratio(self) -> builtins.float:
        r"""
        测试窗口长度（占总数据的比例），默认 0.20
        """
    @test_ratio.setter
    def test_ratio(self, value: builtins.float) -> None:
        r"""
        测试窗口长度（占总数据的比例），默认 0.20
        """
    @property
    def step_ratio(self) -> builtins.float:
        r"""
        滚动步长（占总数据的比例），默认 0.10
        """
    @step_ratio.setter
    def step_ratio(self, value: builtins.float) -> None:
        r"""
        滚动步长（占总数据的比例），默认 0.10
        """
    @property
    def inherit_prior(self) -> builtins.bool:
        r"""
        是否从上一窗口继承权重先验，默认 true
        """
    @inherit_prior.setter
    def inherit_prior(self, value: builtins.bool) -> None:
        r"""
        是否从上一窗口继承权重先验，默认 true
        """
    @property
    def optimizer_config(self) -> OptimizerConfig:
        r"""
        内嵌的单次优化器配置
        """
    @optimizer_config.setter
    def optimizer_config(self, value: OptimizerConfig) -> None:
        r"""
        内嵌的单次优化器配置
        """
    def __new__(
        cls,
        *,
        train_ratio: builtins.float = 0.6,
        test_ratio: builtins.float = 0.2,
        step_ratio: builtins.float = 0.1,
        inherit_prior: builtins.bool = True,
        optimizer_config: typing.Optional[OptimizerConfig] = None,
    ) -> WalkForwardConfig: ...

@typing.final
class WalkForwardResult:
    r"""
    整体向前滚动结果
    """
    @property
    def windows(self) -> builtins.list[WindowResult]: ...
    @property
    def optimize_metric(self) -> builtins.str: ...
    @property
    def aggregate_test_metrics(self) -> builtins.dict[builtins.str, builtins.float]:
        r"""
        样本外总体平均指标
        """

@typing.final
class WindowResult:
    r"""
    单窗口优化结果
    """
    @property
    def window_id(self) -> builtins.int: ...
    @property
    def train_range(self) -> tuple[builtins.int, builtins.int]: ...
    @property
    def test_range(self) -> tuple[builtins.int, builtins.int]: ...
    @property
    def best_params(self) -> SingleParamSet:
        r"""
        最优参数集 (完整结构)
        """
    @property
    def optimize_metric(self) -> builtins.str:
        r"""
        优化目标
        """
    @property
    def train_metrics(self) -> builtins.dict[builtins.str, builtins.float]:
        r"""
        训练集指标
        """
    @property
    def test_metrics(self) -> builtins.dict[builtins.str, builtins.float]:
        r"""
        测试集指标
        """
    @property
    def history(self) -> typing.Optional[builtins.list[RoundSummary]]: ...

@typing.final
class BenchmarkFunction(enum.Enum):
    r"""
    基准函数枚举
    """

    Sphere = ...
    r"""
    Sphere
    """
    Rosenbrock = ...
    r"""
    Rosenbrock
    """
    Rastrigin = ...
    r"""
    Rastrigin
    """
    Ackley = ...
    r"""
    Ackley
    """

@typing.final
class ExecutionStage(enum.Enum):
    r"""
    执行阶段指标枚举
    """

    Idle = ...
    r"""
    空闲/未开始
    """
    Indicator = ...
    r"""
    指标计算
    """
    Signals = ...
    r"""
    信号生成
    """
    Backtest = ...
    r"""
    回测执行
    """
    Performance = ...
    r"""
    性能评估
    """

@typing.final
class LogicOp(enum.Enum):
    r"""
    逻辑操作枚举
    """

    AND = ...
    r"""
    逻辑与
    """
    OR = ...
    r"""
    逻辑或
    """

@typing.final
class OptimizeMetric(enum.Enum):
    r"""
    优化目标指标枚举
    """

    SharpeRatio = ...
    r"""
    年化夏普比率
    """
    SortinoRatio = ...
    r"""
    年化索提诺比率
    """
    CalmarRatio = ...
    r"""
    年化卡尔马比率
    """
    SharpeRatioRaw = ...
    r"""
    非年化夏普比率
    """
    SortinoRatioRaw = ...
    r"""
    非年化索提诺比率
    """
    CalmarRatioRaw = ...
    r"""
    非年化卡尔马比率
    """
    TotalReturn = ...
    r"""
    总回报率
    """
    WinRate = ...
    r"""
    胜率
    """
    ProfitLossRatio = ...
    r"""
    盈亏比
    """
    MaxDrawdown = ...
    r"""
    最大回撤
    """

    def as_str(self) -> builtins.str:
        r"""
        转换为对应的性能指标键名
        """

@typing.final
class ParamType(enum.Enum):
    r"""
    参数类型
    """

    Float = ...
    r"""
    浮点数
    """
    Integer = ...
    r"""
    整数
    """
    Boolean = ...
    r"""
    布尔值
    """

@typing.final
class PerformanceMetric(enum.Enum):
    r"""
    性能指标枚举
    """

    TotalReturn = ...
    r"""
    总回报率
    """
    MaxDrawdown = ...
    r"""
    最大回撤
    """
    MaxDrawdownDuration = ...
    r"""
    最大回撤持续时间
    """
    SharpeRatio = ...
    r"""
    年化夏普比率
    """
    SortinoRatio = ...
    r"""
    年化索提诺比率
    """
    CalmarRatio = ...
    r"""
    年化卡尔马比率
    """
    SharpeRatioRaw = ...
    r"""
    非年化夏普比率（原始）
    """
    SortinoRatioRaw = ...
    r"""
    非年化索提诺比率（原始）
    """
    CalmarRatioRaw = ...
    r"""
    非年化卡尔马比率（原始）
    """
    TotalTrades = ...
    r"""
    总交易次数
    """
    AvgDailyTrades = ...
    r"""
    平均每日交易次数
    """
    WinRate = ...
    r"""
    胜率
    """
    ProfitLossRatio = ...
    r"""
    盈亏比
    """
    AvgHoldingDuration = ...
    r"""
    平均持仓时间
    """
    AvgEmptyDuration = ...
    r"""
    平均空仓时间
    """
    MaxHoldingDuration = ...
    r"""
    最大持仓时间
    """
    MaxEmptyDuration = ...
    r"""
    最大空仓时间
    """
    MaxSafeLeverage = ...
    r"""
    最大安全杠杆
    """
    AnnualizationFactor = ...
    r"""
    年化因子
    """
    HasLeadingNanCount = ...
    r"""
    前置无效数据计数
    """
