# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

__all__ = [
    "resolve_actions",
]

def resolve_actions(
    row_dict: dict,
    symbol: builtins.str,
    sl_exit_in_bar: builtins.bool,
    tp_exit_in_bar: builtins.bool,
) -> typing.Any:
    r"""
    Python绑定：解析 DataFrame 行为字典 (SignalState Dict)
    """
