# File: .github/workflows/release-please.yml

name: Release Please
on:
    push:
        # 确保这里包含您的主分支 (master 或 main)
        branches:
            - master
            - main
permissions:
    # 必须有写入权限才能创建 PR 和推送 Tag
    contents: write
    pull-requests: write
jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{ secrets.RELEASE_PLEASE_TOKEN || secrets.GITHUB_TOKEN }}
                  # 关键：指定 release-type 为 rust
                  release-type: rust
                  # 可选：指定包名，但不是必须的，因为它会从 Cargo.toml 获取
                  package-name: pyo3-quant

                  # 注意：不需要 command: manifest
                  # 注意：不需要 manifest-file: ...
                  # 注意：不需要 config-file: ...
