name: Release Please
on:
    push:
        branches:
            - main
            - master
permissions:
    contents: write
    pull-requests: write
jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{ secrets.RELEASE_PLEASE_TOKEN || secrets.GITHUB_TOKEN }}
                  command: manifest # 对于多语言，使用manifest模式
                  manifest-file: release-please-manifest.json # 见下一步
